# Generated by Django 2.2.6 on 2019-10-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='image_user')),
                ('password', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('date_add', models.DateField()),
                ('date_update', models.DateField()),
                ('staut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
        ),
    ]
