# Generated by Django 2.2.6 on 2019-10-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='image',
            new_name='images',
        ),
    ]
